
spring:
  application:
    name: fastorder-platform

  # database
  datasource:
    url: jdbc:postgresql://localhost:5434/fastorder_db
    username: fastorder
    password: fastorder
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8084