version: "3.9"

services:

  # =========================
  # ðŸ“¡ ZIPKIN (TRACING)
  # =========================
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin-fastorder
    ports:
      - "9411:9411"

  # =========================
  # ðŸ“Š PROMETHEUS (MÃ‰TRICAS)
  # =========================
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-fastorder
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  # =========================
  # ðŸ“ˆ GRAFANA (DASHBOARDS)
  # =========================
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-fastorder
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki

  # =========================
  # ðŸ“œ LOKI (LOG STORAGE)
  # =========================
  loki:
    image: grafana/loki:2.9.3
    container_name: loki-fastorder
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  # =========================
  # ðŸ“¥ PROMTAIL (LOG COLLECTOR)
  # =========================
  promtail:
    image: grafana/promtail:2.9.3
    container_name: promtail-fastorder
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /etc/machine-id:/etc/machine-id:ro
      - ./configs/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml
    command: -config.file=/etc/promtail/promtail-config.yml
    depends_on:
      - loki