version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: fastorder-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: orderdb
    volumes:
      - mongo_data:/data/db
    networks:
      - fastorder-net

  mongo-express:
    image: mongo-express:latest
    container_name: fastorder-mongo-express
    restart: always
    ports:
      - "8088:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: rafael
      ME_CONFIG_BASICAUTH_PASSWORD: MongoExpress2026!
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin123@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - fastorder-net

  kafka:
    image: apache/kafka:latest
    container_name: fastorder-kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - fastorder-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: fastorder-kafka-ui
    restart: always
    ports:
      - "8089:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: fastorder-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - fastorder-net

volumes:
  mongo_data:
  kafka_data:

networks:
  fastorder-net:
    driver: bridge