server:
  port: ${ORDER_SERVER_PORT:8080}

spring:
  config:
    activate:
      on-profile: local

  data:
    mongodb:
      uri: ${ORDER_MONGODB_URI}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${KAFKA_ORDER_CONSUMER_GROUP_ID}
      auto-offset-reset: earliest

app:
  kafka:
    topic-name: ${KAFKA_ORDER_TOPIC_NAME}
    partitions: 3
    replication-factor: 1